version: "3"
services:
  node-server:
    build:
      context: .
      dockerfile: ./docker/development/node-server/Dockerfile
    container_name: english-study-node-server
    working_dir: /app
    volumes:
      - ./server/public/:/app/public/
      - ./.env:/app/.env
      - /app/node_modules
    networks:
      - english_study_network
    tty: true
    ports:
      - ${NODE_SERVER_PORT}:${NODE_SERVER_PORT}
    stdin_open: true
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      DATABASE_URL: ${DATABASE_URL}
      NODE_SERVER_PORT: ${NODE_SERVER_PORT}
      HOST_SERVER: ${HOST_SERVER}
      TOKEN_KEY: ${TOKEN_KEY}
      APP_DEBUG: ${APP_DEBUG}
  node-frontend:
    build:
      context: .
      dockerfile: ./docker/development/node-frontend/Dockerfile
    container_name: english-study-node-frontend
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./client/:/app
      - ./.env:/app/.env
      - /app/node_modules
    networks:
      - english_study_network
    tty: true
    ports:
      - ${NODE_FRONTEND_PORT}:${NODE_FRONTEND_PORT}
    stdin_open: true
    environment:
      TZ: ${TZ}
      REACT_APP_DEBUG: ${APP_DEBUG}
      REACT_APP_HOST_SERVER: ${HOST_SERVER}
      REACT_APP_NODE_SERVER_PORT: ${NODE_SERVER_PORT}
  mysql:
    image: mysql:8.0.26
    container_name: english-study-mysql
    restart: unless-stopped
    tty: true
    ports:
      - ${DB_MYSQL_PORT}:3306
    volumes:
      - ./database:/var/lib/mysql
      - ./database-backup/latest.${DB_MYSQL_DATABASE}.sql.gz:/docker-entrypoint-initdb.d/database.sql.gz
    networks:
      - english_study_network
    command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      TZ: ${TZ}
      MYSQL_DATABASE: ${DB_MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}
      SERVICE_NAME: mysql
  mysql-cron-backup:
    image: fradelg/mysql-cron-backup
    container_name: english-study-mysql-backup
    depends_on:
      - mysql
    volumes:
      - ./database-backup:/backup
    networks:
      - english_study_network
    environment:
      - MYSQL_HOST=english_study_mysql
      - MYSQL_USER=${DB_MYSQL_USERNAME}
      - MYSQL_PASS=${DB_MYSQL_PASSWORD}
      - MAX_BACKUPS=7
      - INIT_BACKUP=1
      - TZ=${TZ}
      - CRON_TIME=0 3 * * *
      - GZIP_LEVEL=9
    restart: unless-stopped
  phpmyadmin:
    build:
      context: .
      dockerfile: docker/development/phpmyadmin/Dockerfile
    container_name: english-study-phpmyadmin
    environment:
      PMA_ARBITRARY: "1"
      PMA_HOST: mysql
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - mysql
    networks:
      - english_study_network
    restart: always
networks:
  english_study_network:
